### PR TITLE
Fix `extra_ref` for test-infra prow jobs

### PR DESCRIPTION
**Pull request by a-hilaly**
Currently `test-infra` prow job pods are failing with:
```bash
{"component":"clonerefs","file":"k8s.io/test-infra/prow/cmd/clonerefs
/main.go:36","func":"main.main","level":"fatal","msg":"Invalid options:
clone ref config 1 (for aws-controllers-k8s/test-infra) will be extracted 
to /home/prow/go/src/github.com/aws-controllers-k8s/test-infra, which
clone ref 0 (for aws-controllers-k8s/test-infra) is also using","severity"
:"fatal","time":"2023-09-07T16:20:53Z"}
```

This patch fixes the error by removing the repository `test-infra` from the `extra_refs` and replaces it with `code-generator` instead. 

`test-infra` is cloned by default in this prow job.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by a-hilaly** [comment]
tested patch and job is running correctly https://prow.ack.aws.dev/view/s3/ack-prow-logs/pr-logs/pull/aws-controllers-k8s_test-infra/226/acktest-ecr-e2e-tests/1699846991959298048

**Review by RedbackThomson — APPROVED** [review]
/lgtm

**Pull request merged**
