### PR TITLE
Use IAM role from AWS account hosting controller images for release-controller.sh script.

### PR DESCRIPTION
**Pull request by vijtrip2**
* Use IAM role from AWS account hosting controller images for release-controller.sh script.
* With new ecr repo migration, we need to use IAM role identity from the new account for publishing controller and chart images.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
Nice, looks kosher to me.

**Comment by jaypipes** [comment]
@vijtrip2 have you added the appropriate SSM parameter value? can I lgtm this?

**Comment by vijtrip2** [comment]
> @vijtrip2 have you added the appropriate SSM parameter value? can I lgtm this?

Yes and Yes : )

**Pull request merged**
