### PR TITLE
Bump Go compiler used to release controllers binaries to 1.21.5

### PR DESCRIPTION
**Pull request by a-hilaly**
We're currently using Go 1.21.0 to build ACK controllers binaries which
are shipped within ACK official official images. This bump protects us
from exposing vulnerable applications (and getting flagged by CVE scanners)
 by keeping up-to-date with the latest available Go version.

A better solution is being built that will automatically bump Go
versions in test-infra repository.

Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by acornett21 — APPROVED** [review]

**Comment by acornett21** [comment]
@a-hilaly Do we need to be pinned to minor versions? Can we be pinned to say `1.21` then on rebuilds we automatically get the fixes in the `dot` version? (non-blocking question)

**Comment by a-hilaly** [comment]
>@a-hilaly Do we need to be pinned to minor versions? Can we be pinned to say 1.21 then on rebuilds we automatically get the fixes in the dot version? (non-blocking question)

I wish googlestorage supported that, but [`1.21` does work here](https://github.com/aws-controllers-k8s/test-infra/blob/main/prow/jobs/images/Dockerfile.deploy#L31) - we can change the way we're doing things in the future.

**Review by acornett21 — APPROVED** [review]

**Review by ivelichkovich — APPROVED** [review]

**Pull request merged**
