### PR TITLE
Make all code-generator pre-submit tests required

### PR DESCRIPTION
**Pull request by A-Hilaly**
Recently, code-generator PRs were being merged as soon as unit tests
passed, regardless of the outcome of the end-to-end tests. This patch
changes that behavior by making the end-to-end tests (including
ec2, lambda, apigatewayv2, iam , ecr, s3 and dynamodb) a requirement for
PRs to be merged.

This change will ensure that code-generator changes are thoroughly
tested before they are merged into the main branch.
Signed-off-by: Amine Hilaly <hilalyamine@gmail.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
:+1: muy bueno.

**Comment by RedbackThomson** [comment]
I would like to reconsider this change. These pre-submit tests were intentionally marked as optional because some changes to the code-generator require changes to the `runtime` which may not yet have been released. With this PR, we are requiring that all changes to the `runtime` are merged and released, and the `code-generator` to consume those changes, before merging any supplementary changes in `code-generator`.

**Comment by jaypipes** [comment]
> I would like to reconsider this change. These pre-submit tests were intentionally marked as optional because some changes to the code-generator require changes to the `runtime` which may not yet have been released. With this PR, we are requiring that all changes to the `runtime` are merged and released, and the `code-generator` to consume those changes, before merging any supplementary changes in `code-generator`.

@RedbackThomson while this is true, it's also true that anyone on `code-generator-maintainer` team can force-merge code, right? So it's possible to treat those kinds of ordered merges specially?

**Comment by A-Hilaly** [comment]
>I would like to reconsider this change. These pre-submit tests were intentionally marked as optional because some changes to the code-generator require changes to the runtime which may not yet have been released. With this PR, we are requiring that all changes to the runtime are merged and released, and the code-generator to consume those changes, before merging any supplementary changes in code-generator.

I agree, however I think it's safer to force merge something manually than having PRs merged before e2e tests finish running. I've seen it happen multiple times.

**Pull request merged**
