### PR TITLE
Migrate from ArgoCD to Flux2

### PR DESCRIPTION
**Pull request by RedbackThomson**
Remove all trace of ArgoCD
- Install Flux2 from Manifest, removing ArgoCD helm chart
- Update any `Application` to `HelmRelease` or `Kustomization` types
- Update documentation to match

### CODE REVIEW

**Review by vijtrip2 — APPROVED** [review]
looks good. I am guessing using 'RedbackThomson' repo is intended for now.

**Comment by RedbackThomson** [comment]
> looks good. I am guessing using 'RedbackThomson' repo is intended for now.

Not intended. I just always forget to change it. Thanks for the heads up

**Pull request merged**
