### PR TITLE
Add SSM inventory reporting

### PR DESCRIPTION
**Pull request by RedbackThomson**
Description of changes:
Adds a new construct with configuration for SSM `GatherInventory` and associated publishing to an S3 bucket.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jaypipes — APPROVED** [review]
Looks kosher to me. Was this something that was mandated by IT or SecOps? Or just some best practices you picked up elsewhere @RedbackThomson?

**Comment by RedbackThomson** [comment]
> Looks kosher to me. Was this something that was mandated by IT or SecOps? Or just some best practices you picked up elsewhere @RedbackThomson?

Yep, PVRE reporting again from SecOps

**Review by A-Hilaly — APPROVED** [review]
Clean :+1:

**Pull request merged**
