### PR TITLE
Optionally inherit the `AWS_PROFILE` env var in `run-e2e-tests.sh`

### PR DESCRIPTION
**Pull request by jljaco**
Useful when executing tests manually using non-default profiles

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by RedbackThomson** [comment]
There is already a section for configuring the tests to run under a given profile name: https://github.com/aws-controllers-k8s/test-infra/blob/main/test_config.example.yaml#L29

Is that sufficient?

**Comment by jljaco** [comment]
> There is already a section for configuring the tests to run under a given profile name: https://github.com/aws-controllers-k8s/test-infra/blob/main/test_config.example.yaml#L29
> 
> Is that sufficient?

When I run a test with `create: false` + `aws.profile: jljaco` (my profile name), I get the following when I have an expired set of `default` credentials:

```
(venv) ✔ ~/go/src/github.com/aws-controllers-k8s/test-infra
21:15 $ make kind-test SERVICE=ec2
2023-01-27T21:15:57 [DEBUG] Debug mode enabled
2023-01-27T21:15:58 [INFO] Testing connection to existing cluster ...
2023-01-27T21:15:58 [DEBUG] Calling kubectl get nodes
2023-01-27T21:15:58 [INFO] Running test bootstrap ...
Traceback (most recent call last):
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/ec2-controller/test/e2e/service_bootstrap.py", line 19, in <module>
    from acktest.bootstrapping.vpc import VPC
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/src/acktest/bootstrapping/vpc.py", line 7, in <module>
    from .. import resources
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/src/acktest/resources.py", line 47, in <module>
    in_str: str, replacement_dictionary: Dict[str, Any] = default_placeholder_values()) -> str:
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/src/acktest/resources.py", line 31, in default_placeholder_values
    "AWS_ACCOUNT_ID": identity.get_account_id(),
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/src/acktest/aws/identity.py", line 20, in get_account_id
    return boto3.client('sts').get_caller_identity().get('Account')
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/venv/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/venv/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid
2023-01-27T21:15:59 [INFO] Running tests ...
ImportError while loading conftest '/local/home/jljaco/go/src/github.com/aws-controllers-k8s/ec2-controller/test/e2e/conftest.py'.
__init__.py:18: in <module>
    from acktest.resources import load_resource_file
../../../test-infra/src/acktest/resources.py:47: in <module>
    in_str: str, replacement_dictionary: Dict[str, Any] = default_placeholder_values()) -> str:
../../../test-infra/src/acktest/resources.py:31: in default_placeholder_values
    "AWS_ACCOUNT_ID": identity.get_account_id(),
../../../test-infra/src/acktest/aws/identity.py:20: in get_account_id
    return boto3.client('sts').get_caller_identity().get('Account')
../../../test-infra/venv/lib/python3.9/site-packages/botocore/client.py:514: in _api_call
    return self._make_api_call(operation_name, kwargs)
../../../test-infra/venv/lib/python3.9/site-packages/botocore/client.py:938: in _make_api_call
    raise error_class(parsed_response, operation_name)
E   botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid
2023-01-27T21:16:00 [ERROR] Tests failed with exit code 4
2023-01-27T21:16:00 [INFO] Running test cleanup ...
Traceback (most recent call last):
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/ec2-controller/test/e2e/service_cleanup.py", line 19, in <module>
    from e2e import bootstrap_directory
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/ec2-controller/test/e2e/__init__.py", line 18, in <module>
    from acktest.resources import load_resource_file
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/src/acktest/resources.py", line 47, in <module>
    in_str: str, replacement_dictionary: Dict[str, Any] = default_placeholder_values()) -> str:
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/src/acktest/resources.py", line 31, in default_placeholder_values
    "AWS_ACCOUNT_ID": identity.get_account_id(),
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/src/acktest/aws/identity.py", line 20, in get_account_id
    return boto3.client('sts').get_caller_identity().get('Account')
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/venv/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/local/home/jljaco/go/src/github.com/aws-controllers-k8s/test-infra/venv/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid
make: *** [kind-test] Error 1
```

**Comment by RedbackThomson** [comment]
These are the lines responsible for actually running the tests:
https://github.com/aws-controllers-k8s/test-infra/blob/main/scripts/pytest-local-runner.sh#L24-L34

and 

https://github.com/aws-controllers-k8s/test-infra/blob/main/scripts/pytest-local-runner.sh#L50-L55

Rather than exporting the `AWS_PROFILE` from the environment variable, could we add them as conditional variables exposed during these commands?

The premise of the `test-infra` config file was to get away from relying on environment variables. Before that, we had a crazy list of env vars that we had to memorise to understand how everything was working. However the AWS credential chain is one part that might still rely on env vars, but if there is a way to do it without them then I'd prefer that

**Comment by RedbackThomson** [comment]
Actually the Docker image that runs those bootstrap and test commands already has this environment variable exposed within it. See https://github.com/aws-controllers-k8s/test-infra/blob/main/scripts/pytest-image-runner.sh#L122

Are you running this with the config `tests.run_locally: true`? (Not inside the Docker container)

**Pull request closed without merging**
